### PR TITLE
no need for regex

### PR DESCRIPTION
**Pull request by jjenzz**

### CODE REVIEW

**Comment by dysphasia** [comment]
this is really cool but it makes the code less robust, in the case that you pass your own string into a function which doesn't have start with "?". i'm torn. gonna think this over!

thank you, btw.

**Comment by jjenzz** [comment]
Ah of course, sorry. I came here from your blog post on medium.com which wasn't passing an optional string! My bad. Should pay more attention before I start firing off pull requests at work to non-work related things ;)

**Comment by dysphasia** [comment]
I appreciate it though! If you don't mind i can update the article with
your alternative solution and a comment about the difference.

Nick

On Thu, Mar 27, 2014 at 2:27 PM, Jenna Smith notifications@github.comwrote:

> Ah of course, sorry. I came here from your blog post on medium.com which
> wasn't passing an optional string! My bad. Should pay more attention before
> I start firing off pull requests at work to non-work related things ;)
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/youbastard/getQueryParameters/pull/1#issuecomment-38842457
> .

## 

Nicholas Ortenzio
nicholas.ortenzio@gmail.com

**Comment by jjenzz** [comment]
Sure, feel free :)

**Comment by dysphasia** [comment]
done :) thanks again

On Fri, Mar 28, 2014 at 4:32 AM, Jenna Smith notifications@github.comwrote:

> Sure, feel free :)
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/youbastard/getQueryParameters/pull/1#issuecomment-38897597
> .

## 

Nicholas Ortenzio
nicholas.ortenzio@gmail.com

**Pull request closed without merging**
